### ISSUE TITLE
Unable to add more than three views

### ISSUE THREAD

**Issue by Gantaios** [eliakorkmaz/Hola#1]
Hi am unable to add more than three views.

**Comment by eliakorkmaz** [comment]
Hi ✋🏽
This problem have solved with this commits 
[Hola File](https://github.com/eliakorkmaz/Hola/commit/ffea78085a956f569ea1ba9950325a6e2dabb960)
[ViewController to Test](https://github.com/eliakorkmaz/Hola/commit/9dcb892bc6bbb103b2566da02011c9cb4e2e9b07)

Thanks for your contribition ●
