### ISSUE TITLE
How to use this using Storyboard (UIView)

### ISSUE THREAD

**Issue by dilipiOSDeveloper** [eliakorkmaz/Hola#2]
how can i use this using storyboard not programmatically, i simply taken a uiview and assigned that view class as "Hola" after that what code i need to change to show my array of images 
i m using like this 
        Hola(frame: CGRect(), imageArray: imageArray, .vertical)

but i m not able to see any image pls help me out

**Comment by eliakorkmaz** [comment]
Hey @diliptiwari333 ,

Thanks for reaching out.
I've solved your problem and add a feature for the Hola.

There is the example.

```
@IBOutlet weak var holaView: Hola!

    override func viewDidLoad() {
        super.viewDidLoad()


        let _image1: UIImage = UIImage(named:"image1")!
        let _image2: UIImage = UIImage(named:"image2")!
        let _image3: UIImage = UIImage(named:"image3")!
        let _image4: UIImage = UIImage(named:"image2")!

        let imageArray: [UIImage] = [_image1,_image2,_image3,_image4]
        let viewArray: [UIView] = [...........yourViews]

        holaView.prepareImagesForStoryboard(uiimageArray: imageArray, rotation: .vertical)

        holaView.prepareViewsForStoryboard(viewArray: viewArray, rotation: .horizontal)

    }
```

Use 

`holaView.prepareImagesForStoryboard(uiimageArray: imageArray, rotation: .vertical)`

or

`holaView.prepareViewsForStoryboard(viewArray: viewArray, rotation: .horizontal)`

depends on which one represents your data.

**Comment by dilipiOSDeveloper** [comment]
Thanks for help will try and let you know

**Comment by dilipiOSDeveloper** [comment]
#2 

![Screen Shot 2019-10-18 at 11 04 26 AM](https://user-images.githubusercontent.com/39292280/67068259-1c613880-f197-11e9-85cc-ff8749026eb9.png)

pls run updated project you created it crashes

**Comment by eliakorkmaz** [comment]
Hey @diliptiwari333 

Are you linked your storyboard UIView into holaView?

Drag & Drop an UIView to Storyboard. Then set it's class to Hola

It must be not linked.

**Comment by dilipiOSDeveloper** [comment]
I did same thing can u share ur working project here with horizontal images
swipe

**Comment by eliakorkmaz** [comment]
I added it. I worked well for me.

**Comment by diliptiwari333** [comment]
Can i share my project which i edited and used

**Comment by dilipiOSDeveloper** [comment]
I now run ur updated project its working with storyboard only one issue i m facing how can i imageView content size to `imageView.contentMode = UIViewContentMode.ScaleAspectFit
` where this only last help i req. 

![Simulator Screen Shot - iPhone 6s - 2019-10-19 at 17 49 26](https://user-images.githubusercontent.com/39292280/67144824-e310f180-f298-11e9-8ef2-2ae7bf31a227.png)
![Simulator Screen Shot - iPhone 6s - 2019-10-19 at 17 49 23](https://user-images.githubusercontent.com/39292280/67144847-2f5c3180-f299-11e9-8daf-ecdb7704b814.png)

my images not looks good as u can see above text of image cuts

**Comment by eliakorkmaz** [comment]
Hey @diliptiwari333 ,

I hope you worked it well.

Go to `Hola.swift` and in `insertImageElements` function edit `UIImageView's` `contentMode` as you wish.

**Comment by dilipiOSDeveloper** [comment]
Can you tell me where

**Comment by eliakorkmaz** [comment]
look at in line 113.

there is a line with
`imageViewArray[i] = UIImageView()`

after this line you have to set your content mode like that.

`imageViewArray[i]!.contentMode = .scaleAspectFit` etc

**Comment by dilipiOSDeveloper** [comment]
Thanks i  will try this

**Comment by eliakorkmaz** [comment]
Hola is not fully automated, for any changes you have to look at Hola.swift and change its styles or somethings.

**Comment by dilipiOSDeveloper** [comment]
Sure and thanks if i will face any issue then i will let you know
